import type { Config } from "tailwindcss";

const config: Config = {
	content: [
		"./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/components/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/app/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		extend: {
			backgroundImage: {
				"gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
				"gradient-conic":
					"conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
			},
			colors: {
				"header-lt": "#d14526",
				"page-lt": "#eeeeee",
				"details-bg-lt": "#ffffff",
				"text-lt": "#262626",
				"favourite-icon-lt": "#acacac",
				"header-dt": "#516289",
				"page-dt": "#374157",
				"details-bg-dt": "#212734",
				"text-dt": "#a1a1a1",
				"type-normal": "#A8A878",
				"type-fire": "#F08030",
				"type-water": "#6890F0",
				"type-grass": "#78C850",
				"type-electric": "#F8D030",
				"type-ice": "#98D8D8",
				"type-fighting": "#C03028",
				"type-ground": "#E0C068",
				"type-poison": "#A040A0",
				"type-flying": "#A890F0",
				"type-psychic": "#F85888",
				"type-ghost": "#705898",
				"type-steel": "#B8B8D0",
				"type-fairy": "#F0B6BC",
				"type-bug": "#A8B820",
				"type-rock": "#B8A038",
				"type-dragon": "#7038F8",
				"type-dark": "#705848",
			},
		},
	},
	plugins: [],
	safelist: [
		"bg-type-normal",
		"bg-type-fire",
		"bg-type-water",
		"bg-type-grass",
		"bg-type-electric",
		"bg-type-ice",
		"bg-type-fighting",
		"bg-type-ground",
		"bg-type-poison",
		"bg-type-flying",
		"bg-type-psychic",
		"bg-type-ghost",
		"bg-type-steel",
		"bg-type-fairy",
		"bg-type-bug",
		"bg-type-rock",
		"bg-type-dragon",
		"bg-type-dark",
	],
};
export default config;
